default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  timeout: 5000

development:
  <<: *default
  database: platform_development

test:
  <<: *default
  database: platform_test

production:
  <<: *default
  database: platform_production
