name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn run build

      - name: Linting
        run: yarn run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn run build

      - name: Create Test DB
        run: yarn run rails db:create

      - name: Precompile
        run: yarn run rails assets:precompile

      - name: Tests
        run: yarn run rails test

  system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn run ci:test:build

      - name: Create Test DB
        run: yarn run ci:test:db

      - name: Tests
        run: yarn run ci:test:system