name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn run build

      - name: Linting
        run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn run build

      - name: Tests
        run: yarn run rails test